import type { StageViewProps } from '../types';
import { Panel, StageFooter, StageIntro, SubmitButton, TextAreaField, Choice, EvidenceShelf } from '../components';

export const meta = { id: 'F05', chapter: '始', title: '真正致毒手法', view: 'endgame' as const };

export default function F05({ state, updateDraft, openEvidence, submit }: StageViewProps) {
  const draft = state.stage_states.F05.draft as { medium?: string; action?: string; body?: string; connectionText?: string };
  return <div className="stage-board"><div className="stage-heading"><h1>真正致毒手法</h1><p>三个空槽只要求物件、正常处理动作和身体结果的关系，不要求施工细节。</p></div><StageIntro question="把媒介 → 动作 → 身体结果连成一条关系。" /><Panel title="三槽手法板"><div className="three-col"><div className="slot"><strong>媒介</strong><Choice selected={draft.medium === 'E031'} onClick={() => { updateDraft('F05', { medium: draft.medium === 'E031' ? '' : 'E031' }); openEvidence('E031', 'view_version_1'); }}>E031｜“始”儿童磁带</Choice></div><div className="slot"><strong>动作</strong><div className="choice-grid"><Choice selected={draft.action === '正常处理'} onClick={() => updateDraft('F05', { action: '正常处理' })}>正常处理</Choice><Choice selected={draft.action === '翻找'} onClick={() => updateDraft('F05', { action: '翻找' })}>翻找</Choice><Choice selected={draft.action === '操作磁带'} onClick={() => updateDraft('F05', { action: '操作磁带' })}>操作磁带</Choice></div></div><div className="slot"><strong>身体结果</strong><Choice selected={draft.body === 'E002'} onClick={() => { updateDraft('F05', { body: draft.body === 'E002' ? '' : 'E002' }); openEvidence('E002', 'view_version_2'); }}>E002｜右拇指新鲜创口</Choice></div></div><TextAreaField label="连接说明" value={draft.connectionText ?? ''} onChange={(value) => updateDraft('F05', { connectionText: value })} placeholder="例如：正常处理造成创口，使蛇毒进入" /><EvidenceShelf title="可选辅助旁证" items={[{ id: 'E026', title: '周枫新伤（不能替代 E002）' }, { id: 'E009', title: '磁带箱背景' }]} selected={[]} onToggle={(id) => openEvidence(id)} /></Panel><StageFooter><SubmitButton onClick={() => submit({ medium: draft.medium, action: draft.action ?? '', body: draft.body, connectionText: draft.connectionText ?? '' })}>连接三槽并提交手法</SubmitButton></StageFooter></div>;
}
